language: ruby
notifications:
  email:
    - adam.hendricksen@gmail.com
rvm:
  - 2.1.0
  - 2.0.0
  - 1.9.3
  - 1.8.7
env:
  - "RAILS_VERSION=4.0"
  - "RAILS_VERSION=3.2"
  - "RAILS_VERSION=3.1"
  - "RAILS_VERSION=3.0"
matrix:
  exclude:
    - rvm: 1.8.7
      env: "RAILS_VERSION=4.0"
